version: '2'
services:
  web:
    image: devblog/blog:latest
    command:  rackup --port 3000 --host 0.0.0.0
    links:
      - db
    environment:
      RACK_ENV: production

  db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog