version: '2'
services:
  bloglb:
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin
    image: rancher/lb-service-haproxy:v0.4.2

  db:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog
    command: postgres -c fsync=off

  admin:
    labels:
      io.rancher.container.pull_image: always
    image: sergkoba/blog:latest-admin
    command:  rackup --port 3000 --host 0.0.0.0
    links:
      - db
    environment:
      RACK_ENV: production
      VIRTUAL_HOST: admin.1devblog.org

  front:
    labels:
      io.rancher.container.pull_image: always
    image: sergkoba/blog:latest
    command:  rackup --port 3001 --host 0.0.0.0
    links:
      - db
    environment:
      RACK_ENV: production
      VIRTUAL_HOST: 1devblog.org