version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog
    command: postgres -c fsync=off

  admin:
    image: sergkoba/blog:latest-admin
    command:  rackup --port 3000 --host 0.0.0.0
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      RACK_ENV: production
      VIRTUAL_HOST: admin.1devblog.org

  front:
    image: sergkoba/blog:latest
    command:  rackup --port 3001 --host 0.0.0.0
    links:
      - db
    ports:
      - "3001:3001"
    environment:
      RACK_ENV: production
      VIRTUAL_HOST: 1devblog.org